version: 2.1

jobs:
  build-and-test:
    working_directory: 
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run:
          command: |
            pip3 install -r requirements.txt
            python3 tests/DecisionBoundaryTest.py
            python3 tests/EvaluationTest.py
            python3 tests/ImbalanceRatioTest.py
            python3 tests/MCCTest.py

workflows:
  build_and_test:
    jobs:
      - build-and-test
