version: 2.1

jobs:
  build-and-test:
    working_directory: 
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run:
          command: |
            pip3 install -r requirements.txt
            python3 setup.py develop
            cd tests
            ./run_tests.sh

workflows:
  build_and_test:
    jobs:
      - build-and-test
